### ISSUE TITLE
Urgent: Flatpak info needs to be added.

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/user#8]
I have had some discussions with Dave. We need two pieces of info in the User Manual. The first is about the role of the flatpak packaging:

---
Our Linux packaging options includes:

  - Native .deb packages for Debian and Ubuntu LTO releases on amd64/x86_64.
  - Flatpak/x86_64 packages for other Linux distributions including non-LTO Ubuntu releases
  - Flatpak/aarch64 packages targeting Raspberry Pie 4 and similar high-end platforms.
  - Native .deb packages for Raspbian/armhf.

Although there are exceptions the community's ambition is to build plugins for all of these platforms.

Note that there are no plans for direct support of the various OS:es used on RPi-4 (aarch64) systems, Flatpak is the only supported packaging for these.

We have been testing the Flatpak packages during  the 5.2.0 cycle. To summarize, we see no performance hit compared to native packages. The compatibility with various distributions is also good. However, there are large downloads involved, especially if OpenCPN is the only Flatpak application on the system.

----

The second is user instructions to run the 5.6.0 Flatpak Beta:

---
Running the OpenCPN Flatpak beta requires a working Flatpak installation. See  https://flatpak.org/setup/ for  platform-specific installation procedures.

Installing and running the beta is done from the command line. Installation:

    $ flatpak install --user  https://flathub.org/beta-repo/appstream/org.opencpn.OpenCPN.flatpakref

Once installed, the beta version will be the default alternative and the one started when clicking on the OpenCPN desktop icon. However, if an earlier version was installed before the beta it is still available and can be started using

    $ flatpak run org.opencpn.OpenCPN//stable

To start the beta from the command line:

    $ flatpak run org.opencpn.OpenCPN//beta

To update the beta to latest version:

    $ flatpak update org.opencpn.OpenCPN//beta

---

@rgleason : Can you find some places  in the User Manual for these two snippets?

**Comment by rgleason** [comment]
Yes. I will next.

**Comment by leamas** [comment]
Thanks. Please report back here with some links when you are ready.

**Comment by rgleason** [comment]
Please see  https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak
by  hvreuver, nohal and rgleason (I had totally forgotten about these.)

**Comment by rgleason** [comment]
Now what do we need to change here, or add?

**Comment by leamas** [comment]
Yes, but that is fir the regular release. Notes above are for running the 5.6.0 beta release, which is different in some respects, and IMHO needs a separate heading like "Running the 5.6.0 Flatpak Beta"

**Comment by rgleason** [comment]
First we are using 20.04

**Comment by rgleason** [comment]
Ok That is fine, we can do that and in the meantime be updating the other pages!

**Comment by leamas** [comment]
> First we are using 20.04

yes, but this is not visible for users, it's handled by flatpak.

**Comment by rgleason** [comment]
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak:witho560

One page

**Comment by leamas** [comment]
Thanks, that was actually the urgen part. Rest of it is also important, but not highest priority.

**Comment by rgleason** [comment]
Now I think it shows up better.

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:linux:o560

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak:witho560

**Comment by rgleason** [comment]
Any adjustments needed?

**Comment by leamas** [comment]
None I'm aware of.

**Comment by rgleason** [comment]
Added a blank page to make the bullets, so it shows up better 
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak:witho560

**Comment by rgleason** [comment]
If you need anything else changed let me know, or I can certainly add you as editor using your email and "Leamas"

**Comment by leamas** [comment]
I prefer if you can do it. And yes, while we are on the FAQ, this is also wrong:

_Q: What about Plugins? A: OpenPCN Flatpak relies on the managed plugin interface introduced in version 5.1 (Beta). There are no “legacy” plugins available for OpenCPN Flatpak. Some number of popular managed plugins are available for OpenCPN Flatpak now, more are on the horizon. You can help us prioritize resources by telling us which plugins are missing from OpenCPN Flatpak, that you would really like to see_ 

Correct answer: _A: OpenPCN Flatpak relies on the managed plugin interface introduced in version 5.1 (Beta). There are no “legacy” plugins available for OpenCPN Flatpak. Almost all plugins available as managed plugins are also available for Flatpak"_

**Comment by rgleason** [comment]
Fixed

**Comment by leamas** [comment]
ok

**Comment by leamas** [comment]
My turn to re-open. It's late here. We are still missing the other snippet on packaging strategies, right?

**Comment by rgleason** [comment]
No   look to the left at the index please

**Comment by rgleason** [comment]
From above Alec

Now I think it shows up better.

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:linux:o560

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak:witho560

**Comment by rgleason** [comment]
Close when you've found it. OK?

**Comment by leamas** [comment]
Nope, I don't find this:

---
Our Linux packaging options includes:

  - Native .deb packages for Debian and Ubuntu LTS releases on amd64/x86_64.
  - Flatpak/x86_64 packages for other Linux distributions including non-LTS Ubuntu releases
  - Flatpak/aarch64 packages targeting Raspberry Pie 4 and similar high-end platforms.
  - Native .deb packages for Raspbian/armhf.

Although there are exceptions the community's ambition is to build plugins for all of these platforms.

Note that there are no plans for direct support of the various OS:es used on RPi-4 (aarch64) systems, Flatpak is the only supported packaging for these.

We have been testing the Flatpak packages during  the 5.2.0 cycle. To summarize, we see no performance hit compared to native packages. The compatibility with various distributions is also good. However, there are large downloads involved, especially if OpenCPN is the only Flatpak application on the system.

----

**Comment by rgleason** [comment]
This is the link from abbove
Now I think it shows up better.

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:linux:o560
